---

- name: Converge
  hosts: all
  vars:
    timesync_timezone: UTC
    timesync_ntp_servers: ['0.nl.pool.ntp.org', '1.nl.pool.ntp.org', '2.nl.pool.ntp.org', '3.nl.pool.ntp.org']
  tasks:
    - name: Include role 'ansible-role-timesync'
      include_role:
        name: ansible-role-timesync
